apiVersion: apps/v1
kind: Deployment
metadata:
  name: nc-frontend
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: nc-frontend
  template:
    metadata:
      labels:
        app: nc-frontend
    spec:
      containers:
      - name: nc-frontend
        image: ayubahmed0/nc-project-frontend
        ports:
        - containerPort: 80
        env:
          - name: VITE_API_BASE_URL
            value: {{ .Values.env.VITE_API_BASE_URL }}