version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  node: circleci/node@5.1.0
jobs:
  build-and-test-java-backend:
    working_directory: ~/ce-team-project
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
          working_directory: ~/ce-team-project/ce-team-project-backend
      - run:
          name: Test
          command: mvn test
          working_directory: ~/ce-team-project/ce-team-project-backend
  build-image-and-push-java-backend:
    working_directory: ~/ce-team-project/ce-team-project-backend
    docker:
      - image: cimg/aws:2023.05
    steps:
      - setup_remote_docker 
      - aws-ecr/build-and-push-image:
          repo: ce-project-backend
          path: "ce-team-project-backend" 
          build-path: "ce-team-project-backend" 
          tag: latest 
          public-registry-alias: r3f7r2l5
          public-registry: true

  build-and-test-js-frontend:
    docker:
      - image: cimg/node:18.12.1
    working_directory: ~/ce-team-project
    steps:
      - checkout
      - run: cd ce-team-project-frontend && npm install
 
      - run: cd ce-team-project-frontend && npm test
  build-image-and-push-js-frontend:
    working_directory: ~/ce-team-project/ce-team-project-frontend
    docker:
      - image: cimg/aws:2023.05
    steps:
      - setup_remote_docker 
      - aws-ecr/build-and-push-image:
          repo: ce-project-frontend
          path: "ce-team-project-frontend" 
          build-path: "ce-team-project-frontend" 
          tag: latest 
          public-registry-alias: r3f7r2l5
          public-registry: true
workflows:
  nc-app-pipeline: 
    jobs:
      - build-and-test-java-backend
      - build-image-and-push-java-backend:
          requires: 
            - build-and-test-java-backend 
      - build-and-test-js-frontend
      - build-image-and-push-js-frontend:
          requires:
            - build-and-test-js-frontend