# Default values for nc-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  type: LoadBalancer
  port: 3000

env:
  VITE_API_BASE_URL: "*"