apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    app.kubernetes.io/part-of: nc-backend
  annotations:
    prometheus.io/port: "metrics-port"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: nc-backend
  ports:
    - protocol: TCP
      port: 8080
      name: metrics-port
      targetPort: 8080
  type: LoadBalancer