apiVersion: v1
kind: Service
metadata:
  name: nc-backend-service
spec:
  selector:
    app: nc-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}