apiVersion: apps/v1
kind: Deployment
metadata:
  name: nc-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nc-backend
  template:
    metadata:
      labels:
        app: nc-backend
    spec:
      containers:
        - name: nc-backend
          image: ayubahmed0/nc-project-backend
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            - name: DB_USERNAME
              value: {{ .Values.env.DB_USERNAME }}
            - name: DB_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
